
.PHONY:all
all:
	@echo "CC = $(CC)"
	@echo "AS = $(AS)"
	@echo "CXX = $(CXX)"
	@echo "AR = $(AR)"
	@echo "CFLAGS = $(CFLAGS)"
	@echo "CXXFLAGS = $(CXXFLAGS)"
	@echo "ASFLAGS = $(ASFLAGS)"
	@echo "ARFLAGS = $(ARFLAAGS)"
	@echo "LDFLAGS = $(LDFLAGS)"
